# version: "3"
version: "2"
services:
 # phala-node:
 #   image: ${NODE_IMAGE}
 #   container_name: phala-node
 #   hostname: phala-node
 #   ports:
 #    - "9933:9933"
 #    - "9934:9934"
 #    - "9944:9944"
 #    - "9945:9945"
 #    - "30333:30333"
 #    - "30334:30334"
 #   environment:
 #    - NODE_NAME=${NODE_NAME}
 #    - NODE_ROLE=MINER
 #   volumes:
 #    - ${NODE_VOLUMES}

 phala-pruntime:
   image: ${PRUNTIME_IMAGE}
   container_name: phala-pruntime
   hostname: phala-pruntime
   restart: always
   ports:
    - "8000:8000"
   devices:
     - "/dev/sgx/enclave:/dev/sgx/enclave"
     - "/dev/sgx/provision:/dev/sgx/provision"
     - "/dev/sgx_enclave:/dev/sgx_enclave"
     - "/dev/sgx_provision:/dev/sgx_provision"

   environment:
    - EXTRA_OPTS=--cores=${CORES}
    - ROCKET_ADDRESS=0.0.0.0
   volumes:
    - ${PRUNTIME_VOLUMES}

 phala-pherry:
   image: ${PHERRY_IMAGE}
   container_name: phala-pherry
   hostname: phala-pherry
   restart: always
   depends_on:
    # - phala-node
    - phala-pruntime
   entrypoint:
    [
      "/root/pherry",
      "-r",
      "--parachain",
      "--mnemonic=${MNEMONIC}",
      "--substrate-ws-endpoint=ws://phala-node:9945",             # phala-node 替换为phala-node所在机器ip
      "--collator-ws-endpoint=ws://phala-node:9944",              # phala-node 替换为phala-node所在机器ip
      "--pruntime-endpoint=http://phala-pruntime:8000",
      "--operator=${OPERATOR}",
      "--fetch-blocks=512",
      "--auto-restart"
    ]
