global:
  resolve_timeout: 5m
#   smtp_smarthost: 'smtp.163.com:465'            # 邮箱smtp服务器代理，启用SSL发信, 端口一般是465
#   smtp_from: 'alert@163.com'                    # 发送邮箱名称
#   smtp_auth_username: 'alert@163.com'           # 邮箱名称
#   smtp_auth_password: 'password'                # 邮箱密码或授权码
#   smtp_require_tls: false

route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  group_by: ['alertname']

  routes:
    - receiver: 'default'
      group_wait: 10s
      # group_interval: 10s
      # repeat_interval: 5m
      match_re:
         severity: warning
    - receiver: 'machine'
      group_wait: 10s
      match_re:
         severity: critical

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']

receivers:
- name: 'default'
  webhook_configs:
  - url: 'http://192.168.2.100:8060/dingtalk/default/send'
    send_resolved: true
- name: 'machine'
  webhook_configs:
  - url: 'http://192.168.2.100:8060/dingtalk/machine/send'
    send_resolved: true
